name: Organization Policy Constraint Request
description: Request a constraint exemption for organization policies.
title: "[Constraint]: "
labels: ["constraint", "exemption"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **👋 Please fill in the following information about your constraint request clearly.**
        ---
  
  - type: input
    id: constraint_name
    attributes:
      label: Constraint Name
      description: Enter the full name of the constraint you're applying.
      placeholder: e.g., ainotebooks.restrictPublicIp
    validations:
      required: true
  
  - type: dropdown
    id: constraint_type
    attributes:
      label: Constraint Type
      description: Choose the type of the constraint.
      options:
        - Boolean
        - List
    validations:
      required: true
  
  - type: markdown
    attributes:
      value: |
        **⚠️ Fill out the following fields ONLY if you selected "List" above.**
        ---
  
  - type: dropdown
    id: access_decision
    attributes:
      label: Access Decision (List Constraints Only)
      description: Select the access decision for your list constraint.
      options:
        - Allow
        - Deny
    validations:
      required: false
  
  - type: dropdown
    id: apply_to_all
    attributes:
      label: Apply to All or Specific Values? (List Constraints Only)
      description: Do you want to apply this constraint to all or specific values?
      options:
        - All Values
        - Specific Values
    validations:
      required: false
  
  - type: textarea
    id: specific_values
    attributes:
      label: Specific Values (if applicable)
      description: |
        If you selected "Specific Values" above, enter each value on a new line.
      placeholder: |
        organizations/1234567890
        folders/0987654321
    validations:
      required: false
  
  - type: textarea
    id: reason
    attributes:
      label: Reason for Constraint Request
      description: Clearly describe why you require this constraint.
    validations:
      required: true
