name: Org Policy Constraint Issue
description: File an organization policy constraint issue so that valid personalls will be able to accept your request.
title: "[Constraint]: "
labels: ["constraint", "exemption"]
assignees: ["Tacash444"]
body:
  - type: input
    id: constraint_name
    attributes:
      label: Constraint Name
      description: What is the name of the organization policy constraint you are trying to apply?
      placeholder: ainotebooks.restrictPublicIp
    validations:
      required: true
- type: dropdown
    id: types
    attributes:
      label: Type:
      multiple: false
      options:
        - Boolean
        - List

