name: Basic Issue File Creation

on:
  issues:
    types: [opened]

jobs:
  create-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create hello.txt file
        run: |
          echo "Hello from issue #${{ github.event.issue.number }}" > hello.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated commit: hello.txt created for issue #${{ github.event.issue.number }}"
