name: Create Branch and PR on Issue

on:
  issues:
    types: [opened]

jobs:
  create-branch-and-pr:
    if: contains(toJson(github.event.issue.labels), 'constraint')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create new branch and file from issue body
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          BRANCH_NAME="issue-${ISSUE_NUMBER}"
          git checkout -b "$BRANCH_NAME"

          # Just echo the body into a file (multiline should be preserved by echo with quotes)
          echo "${{ github.event.issue.body }}" > issue_body.yaml

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add file for issue #${ISSUE_NUMBER}"
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Open Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const branchName = `issue-${issueNumber}`;
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Issue #${issueNumber} - Auto-generated PR`,
              head: branchName,
              base: 'main',
              body: `This pull request was automatically created from issue #${issueNumber}. The issue body has been committed as 'issue-${issueNumber}.md'.`
            });
