name: Create Branch and PR on Issue

on:
  issues:
    types: [opened]

jobs:
  create-branch-and-pr:
    # ✅ Run only when BOTH labels are present
    if: |
      contains(github.event.issue.labels.*.name, 'constraint') &&
      contains(github.event.issue.labels.*.name, 'exemption')

    runs-on: ubuntu-latest
    permissions:
      contents: write          # push new branch
      pull-requests: write     # open PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #---------------------------------------------
      # 1. Create branch and commit the issue body
      #---------------------------------------------
      - name: Capture issue body in a file and push branch
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          set -euo pipefail

          BRANCH_NAME="issue-${ISSUE_NUMBER}"
          git switch -c "$BRANCH_NAME"

          # Save the raw issue body
          printf '%s\n' "${{ github.event.issue.body }}" > "issue-${ISSUE_NUMBER}.md"

          # Optional: extract the “Constraint Name” line from the markdown
          CONSTRAINT_NAME=$(grep -A1 '^### Constraint Name' "issue-${ISSUE_NUMBER}.md" | tail -n1 | xargs)
          echo "Constraint name: $CONSTRAINT_NAME"

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add "issue-${ISSUE_NUMBER}.md"
          git commit -m "docs: capture body of issue #${ISSUE_NUMBER}"
          git push --set-upstream origin "$BRANCH_NAME"

      #---------------------------------------------
      # 2. Open a pull request from that branch
      #---------------------------------------------
      - name: Open pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.issue.number;
            const branch = `issue-${issue}`;

            await github.rest.pulls.create({
              ...context.repo,
              title: `Issue #${issue} – auto‑generated PR`,
              head: branch,
              base: 'main',          // 🔵  change if your default branch is not 'main'
              body: `Closes #${issue}\n\nThis PR was created automatically from the issue body.`
            });
