name: Create Branch and PR on Issue

on:
  issues:
    types: [opened]

jobs:
  create-branch-and-pr:
    if: |
      contains(github.event.issue.labels.*.name, 'constraint') &&
      contains(github.event.issue.labels.*.name, 'exemption')

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install --quiet pyyaml

      - name: Create branch & save issue body
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY:   ${{ github.event.issue.body }}
        run: |
          BRANCH="issue-${ISSUE_NUMBER}"
          git switch -c "$BRANCH"
          mkdir -p tmp
          printf '%s\n' "$ISSUE_BODY" > tmp/body.md

      - name: Generate policy file
        run: |
          python "1 - YAML LZ Configuration/OrgPolicyConstraints/output.py" \
                 tmp/body.md \
                 "1 - YAML LZ Configuration/policies"

      - name: Commit & push
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          BRANCH: issue-${{ github.event.issue.number }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tmp/body.md "1 - YAML LZ Configuration/policies/"
          git commit -m "feat: policy from issue #${ISSUE_NUMBER}" || echo "Nothing to commit"
          git push --set-upstream origin "$BRANCH"

      - name: Open pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const n   = context.issue.number;
            const ref = `issue-${n}`;
            await github.rest.pulls.create({
              ...context.repo,
              title: `Issue #${n} – auto-generated policy`,
              head: ref,
              base: 'main',
              body: `Closes #${n}\n\nPolicy generated automatically from the issue form.`
            });
